### ISSUE TITLE
No remote receiving after use api or button

### ISSUE THREAD

**Issue by thomasdebans** [incmve/Itho-WIFI-remote#2]
After reboot remote signal is received.
But when using the api or the button one time, the remote signal doesn't come in anymore.

**Comment by incmve** [comment]
Strange, I didn't check the receiving part after the last update. I will have a look later today.

**Comment by incmve** [comment]
I think I have broken my tranceiver, I can't send or receive anything.
Ordered a new one but that will take some time, if you find anything that might fix it please create a pull request.

**Comment by edjeed** [comment]
After sending a command initReceive must be called, to set the CC1101 in Receive state for receiving message1

**Comment by incmve** [comment]
Thanks 👍
