### ISSUE TITLE
ai-thinker ssid on nodemcu

### ISSUE THREAD

**Issue by matthijsf** [incmve/Itho-WIFI-remote#5]
When flashing this sketch to a ESP-12e (NODEMCU) a SSID named: "ai-thinker ssid-[deviceid}" is permanently broadcasting. The wifi chip needs to be told not to broadcast this. adding the following setting to the Setup part of the sketch fixes this:
```
// Setup
void setup(void)
{
WiFi.mode(WIFI_STA);
}
```

**Comment by incmve** [comment]
Thanks.
